---
- name: synchronize project file slave1 -> master
  hosts: web_servers[0]
  become: yes

  tasks:
    - name: control of existing hello-1.0.war on slave1-node
      stat:
        path: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      register: war

    - name: copy project to master node
      synchronize:
        src: '/tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war'
        dest: '/tmp'
        mode: pull
      when: war.stat.exists

- name: check file on master
  hosts: localhost
  connection: local
  become: no

  tasks:
    - name: control of existing hello-1.0.war in local directory
      stat:
        path: /tmp/hello-1.0.war
      register: war

- name: synchronize project file master -> slave2
  hosts: web_servers[1]
  become: yes

  tasks:
    - name: copy project file from master to slave2 if file exists
      copy:
          src: /tmp/hello-1.0.war
          dest: /tmp/hello-1.0.war
          mode: '0644'
      when: hostvars['localhost'].war.stat.exists

    - name: Move to tomcat webapps directory
      shell: |
        mv /tmp/hello-1.0.war /var/lib/tomcat9/webapps/hello-1.0.war
        chown tomcat:tomcat /var/lib/tomcat9/webapps/hello-1.0.war
        chmod 644 /var/lib/tomcat9/webapps/hello-1.0.war
      args:
        executable: /bin/bash
      when: hostvars['localhost'].war.stat.exists
...