---
- name: deploy project with tomcat in container
  hosts: web_servers[1]
  become: yes

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: install needed software
      apt:
        name:
          - docker.io
        state: present

    - name: install YC
      shell: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | sudo bash -s -- -i /usr/local
        export PATH=$PATH:/usr/local/bin
        yc --version
      args:
        chdir: /tmp

    - name: send key for docker ( 1. for reg to registry, 2. for build image )
      copy:
        src: /tmp/ansible_key.json
        dest: /tmp/
        mode: '0644'

    - name: docker registration and run image from registry
      shell: |
        sudo yc config set service-account-key /tmp/ansible_key.json
        sudo yc container registry configure-docker
        sudo docker run -d -p 8080:8080 cr.yandex/crpirf1t243rd4chrqfd/prod:latest
...